
@echo off
rem generated by doall.sh, consider not to edit

cl /O2 gen_random.c


type 01.manual > 01
type 02.manual > 02
type 03.manual > 03
type 04.manual > 04
gen_random.exe 200 239000 > 05
gen_random.exe 220 239001 > 06
gen_random.exe 242 239002 > 07
gen_random.exe 266 239003 > 08
gen_random.exe 292 239004 > 09
gen_random.exe 321 239005 > 10
gen_random.exe 353 239006 > 11
gen_random.exe 388 239007 > 12
gen_random.exe 426 239008 > 13
gen_random.exe 468 239009 > 14
gen_random.exe 514 239010 > 15
gen_random.exe 565 239011 > 16
gen_random.exe 621 239012 > 17
gen_random.exe 683 239013 > 18
gen_random.exe 751 239014 > 19
gen_random.exe 826 239015 > 20
gen_random.exe 908 239016 > 21
gen_random.exe 998 239017 > 22
gen_random.exe 1097 239018 > 23
gen_random.exe 1206 239019 > 24
gen_random.exe 1326 239020 > 25
gen_random.exe 1458 239021 > 26
gen_random.exe 1603 239022 > 27
gen_random.exe 1763 239023 > 28
gen_random.exe 1939 239024 > 29
gen_random.exe 2132 239025 > 30
gen_random.exe 2345 239026 > 31
gen_random.exe 2579 239027 > 32
gen_random.exe 2836 239028 > 33
gen_random.exe 3119 239029 > 34
gen_random.exe 3430 239030 > 35
gen_random.exe 3773 239031 > 36
gen_random.exe 4150 239032 > 37
gen_random.exe 4565 239033 > 38
gen_random.exe 5021 239034 > 39
gen_random.exe 5523 239035 > 40
gen_random.exe 6075 239036 > 41
gen_random.exe 6682 239037 > 42
gen_random.exe 7350 239038 > 43
gen_random.exe 8085 239039 > 44
gen_random.exe 8893 239040 > 45
gen_random.exe 9782 239041 > 46
gen_random.exe 10000 239042 > 47
gen_random.exe 10000 239043 > 48
gen_random.exe 10000 239044 > 49
gen_random.exe 10000 239045 > 50
gen_random.exe 10000 239046 > 51
gen_random.exe 10000 239047 > 52
gen_random.exe 10000 239048 > 53
gen_random.exe 10000 239049 > 54
echo 10000 10000 10000> 55
echo 0 10000 10000> 56
echo 0 9999 10000> 57
echo 5000 8660 10000> 58
echo 5000 8661 10000> 59
echo 4000 3000 10000> 60
